import React from 'react'

export default function Abot() {
  return (
    <div>EXPLORE A LAKESIDE ADVENTURE WITH THE ENTIRE HIKE TRACING THE WATER'S EDGE. DISCOVER A NATURAL SWIMMING HAVEN FOR PETS, CREATING A PERFECT RETREAT IN NATURE. ITS A BEFINER LEVEL EASY HIKE. PERFECT FOR EVERY AGE GROUP</div>
  )
}
